# Site settings
title: lazyproof blog
email:  lazyproof@users.noreply.github.com
description: lazyproof blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lazyproof.github.io" # the base hostname & protocol for your site
twitter_username: lazyproof
github_username:  lazyproof

# Build settings
markdown: kramdown

permalink: /:title
